//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.8813
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piano.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Piano.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream _do {
            get {
                return ResourceManager.GetStream("_do", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream do1 {
            get {
                return ResourceManager.GetStream("do1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream fa {
            get {
                return ResourceManager.GetStream("fa", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream fa1 {
            get {
                return ResourceManager.GetStream("fa1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream la {
            get {
                return ResourceManager.GetStream("la", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream mi {
            get {
                return ResourceManager.GetStream("mi", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream mi1 {
            get {
                return ResourceManager.GetStream("mi1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream re {
            get {
                return ResourceManager.GetStream("re", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream re1 {
            get {
                return ResourceManager.GetStream("re1", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream si {
            get {
                return ResourceManager.GetStream("si", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream sol {
            get {
                return ResourceManager.GetStream("sol", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon иконка {
            get {
                object obj = ResourceManager.GetObject("иконка", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
